#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

APP_HOME=$( cd "$( dirname "$0" )" && pwd )
APP_NAME="Gradle"
APP_BASE_NAME="gradlew"

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -z "$JAVA_EXE" ]; then
    if [ -n "$JAVA_HOME" ]; then
        JAVA_EXE="$JAVA_HOME/bin/java"
    else
        JAVA_EXE=java
    fi
fi

set -- \
        "-classpath" "$CLASSPATH" \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

exec "$JAVA_EXE" "$@"
